### PR TITLE
Alaska SLDLs

### PR DESCRIPTION
**Pull request by mileswwatkins**

### CODE REVIEW

**Comment by mileswwatkins** [comment]
Issues:
1. All properties besides ID field dropped during

``` make
topo/us-%-sldl.json: shp/%/sldl.shp
    mkdir -p $(dir $@)
    node_modules/.bin/topojson \
        -o $@ \
        --no-pre-quantization \
        --post-quantization=1e6 \
        --simplify=3e-8 \
        --id-property=+GEOID \
        --properties NAMELSAD \
        -- $<
```
1. ID field lost during

``` make
geojson/%/sldl.json: topo/us-%-sldl.json
    node_modules/.bin/topojson-geojson -o geojson/ak \
        --id-property=+id \
        --properties NAMELSAD \
        $<
```
1. Had to hard-code Alaska's postal code in, so this code isn't actually generalizable:

```
    node_modules/.bin/topojson-geojson -o geojson/ak \
```

**Comment by mileswwatkins** [comment]
@anandthakker: See issues above.

**Comment by mileswwatkins** [comment]
On the upside, it does look like `GEOID` lines up with the `reportingUnitID` in the AP `subunit` data!

**Comment by anandthakker** [comment]
Shweeet

**Pull request merged**
